import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request';
import { useEffect, useState } from 'react';
import { printIntrospectionSchema } from 'graphql';
import BlogCard from '../components/BlogCard';

const graphcms = new GraphQLClient('https://api-sa-east-1.graphcms.com/v2/cl5dbsxg202y801uh6zud91xd/master');

const QUERY = gql`
  {
      posts{
        id
        title
        date_publish
        slug
        content {
          html
        }
        author{
          name
          avatar{
            url
          }
        }
        coverPhoto{
              url
        }
      }
  }
`
export async function getStaticProps(){
  const {posts} = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}
export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      </main>
      {posts.map((post) => (
        <BlogCard title={post.title} author={post.author} coverPhoto={post.coverPhoto} key={post.id} datePublished={post.date_publish} slug={post.slug} />
      ))}
      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
